// Generated by scripts/package-plugins.mjs. Do not edit manually.
export const pluginArtifactVersion = "1.2.0" as const;

export const pluginArtifacts = {
  chromium: "/downloads/inbox-rs-chromium-1.2.0.zip",
  firefox: "/downloads/inbox-rs-firefox-1.2.0.xpi",
  thunderbird: "/downloads/inbox-rs-thunderbird-1.2.0.xpi",
} as const;
