// Generated by scripts/package-plugins.mjs. Do not edit manually.
export const pluginArtifactVersion = "0.2.3" as const;

export const pluginArtifacts = {
  chromium: "/downloads/inbox-rs-chromium-0.2.3.zip",
  firefox: "/downloads/inbox-rs-firefox-0.2.3.xpi",
  thunderbird: "/downloads/inbox-rs-thunderbird-0.2.3.xpi",
} as const;
