<script lang="ts">
 import { connected,userSettings,updateUserSettings } from '../../lib/stores'; import {layout,setLayoutPersisted} from '../../lib/layout'; import {ACCENTS,ACCENT_LABELS,ACCENT_SWATCHES,applyAccent,applyMode,applyPalette,isAccent,isPalette,PALETTES,PALETTE_LABELS,type Accent,type Mode,type Palette} from '../../lib/theme';
 const read=(k:string)=>{try{return localStorage.getItem(k)}catch{return null}}; const savedAccent=read('inbox-rs:accent'); const savedPalette=read('inbox-rs:palette'); let localTheme=$state<Mode>((read('inbox-rs:theme') as Mode)||'system'); let accent=$state<Accent>(isAccent(savedAccent)?savedAccent:'indigo'); let palette=$state<Palette>(isPalette(savedPalette)?savedPalette:'solarized'); const theme=$derived($userSettings.theme??localTheme);
 function store(k:string,v:string){try{localStorage.setItem(k,v)}catch{}} function setTheme(v:Mode){localTheme=v;store('inbox-rs:theme',v);applyMode(v);if($connected)void updateUserSettings({theme:v})} function setAccent(v:Accent){accent=v;store('inbox-rs:accent',v);applyAccent(v)} function setPalette(v:Palette){palette=v;store('inbox-rs:palette',v);applyPalette(v)}
</script>
<div class="settings-section"><div class="row stack"><div class="row-main"><div class="row-label">Theme</div></div><div class="row-ctl picks">{#each ['system','light','dark'] as option}<button class="pick" class:on={theme===option} type="button" onclick={()=>setTheme(option as Mode)}><span class="mini {option}"><i></i><i></i><b></b><b></b></span><span>{option==='system'?'Match system':option[0].toUpperCase()+option.slice(1)}</span></button>{/each}</div></div>
<div class="row stack"><div class="row-main"><div class="row-label">Accent colour · {ACCENT_LABELS[accent]}</div><div class="row-desc">This browser only.</div></div><div class="row-ctl swatches">{#each ACCENTS as a}<button type="button" class="swatch" class:on={accent===a} style={`--sw:${ACCENT_SWATCHES[a]}`} aria-label={ACCENT_LABELS[a]} aria-pressed={accent===a} onclick={()=>setAccent(a)}></button>{/each}</div></div>
<div class="row"><div class="row-main"><div class="row-label">Palette</div><div class="row-desc">Neutral tones behind the accent. This browser only.</div></div><div class="row-ctl seg">{#each PALETTES as p}<button type="button" class:on={palette===p} onclick={()=>setPalette(p)}>{PALETTE_LABELS[p]}</button>{/each}</div></div>
<div class="row stack"><div class="row-main"><div class="row-label">Navigation</div><div class="row-desc">Where your groups and collections live. This browser only.</div></div><div class="row-ctl picks">{#each [['classic','Top tabs'],['sidebar','Sidebar']] as option}<button class="pick" class:on={$layout===option[0]} type="button" onclick={()=>setLayoutPersisted(option[0] as 'classic'|'sidebar')}><span class="mini {option[0]}"><i></i><i></i><b></b><b></b></span><span>{option[1]}</span></button>{/each}</div></div></div>
<style>.picks{display:flex!important;gap:.6rem}.pick{width:106px;border:0;background:none;color:var(--text);text-align:left}.pick .mini{display:grid;grid-template-columns:repeat(2,1fr);gap:4px;height:66px;padding:18px 7px 7px;border:1.5px solid var(--border);border-radius:10px;background:#f8f9fb}.pick .mini.dark{background:#0f1117}.pick .mini.system{background:linear-gradient(90deg,#f8f9fb 50%,#0f1117 50%)}.pick .mini.sidebar{grid-template-columns:14px 1fr}.pick .mini i,.pick .mini b{background:#7b849733;border-radius:2px}.pick.on .mini{border-color:var(--accent);box-shadow:0 0 0 3px var(--accent-subtler)}.pick>span:last-child{display:block;margin-top:.4rem;font-size:.79rem}.swatches{display:grid!important;grid-template-columns:repeat(7,36px);gap:.55rem}.swatch{width:32px;height:32px;border-radius:50%;border:2px solid transparent;background:var(--sw)}.swatch.on{box-shadow:0 0 0 2px var(--surface),0 0 0 4px var(--sw)}@media(max-width:767px){.swatches{grid-template-columns:repeat(7,minmax(0,1fr))}.swatch{width:100%;aspect-ratio:1;height:auto}}</style>
