<script lang="ts">
 import { connected,userSettings,updateUserSettings } from '../../lib/stores'; import {layout,setLayoutPersisted} from '../../lib/layout'; import {ACCENTS,ACCENT_LABELS,ACCENT_SWATCHES,applyAccent,applyMode,applyPalette,isAccent,isPalette,PALETTES,PALETTE_DESCRIPTIONS,PALETTE_LABELS,PALETTE_PREVIEWS,type Accent,type Mode,type Palette} from '../../lib/theme';
 const read=(k:string)=>{try{return localStorage.getItem(k)}catch{return null}}; const savedAccent=read('inbox-rs:accent'); const savedPalette=read('inbox-rs:palette'); let localTheme=$state<Mode>((read('inbox-rs:theme') as Mode)||'system'); let accent=$state<Accent>(isAccent(savedAccent)?savedAccent:'indigo'); let palette=$state<Palette>(isPalette(savedPalette)?savedPalette:'solarized'); const theme=$derived($userSettings.theme??localTheme);
 function store(k:string,v:string){try{localStorage.setItem(k,v)}catch{}} function setTheme(v:Mode){localTheme=v;store('inbox-rs:theme',v);applyMode(v);if($connected)void updateUserSettings({theme:v})} function setAccent(v:Accent){accent=v;store('inbox-rs:accent',v);applyAccent(v)} function setPalette(v:Palette){palette=v;store('inbox-rs:palette',v);applyPalette(v)}
 /* Hovering (mouse) or focusing a palette card previews it live; leaving restores the chosen one. Touch skips the preview since tap = choose. */
 function previewPalette(e:PointerEvent|FocusEvent,p:Palette){if('pointerType' in e&&e.pointerType!=='mouse')return;applyPalette(p)} function endPreview(){applyPalette(palette)}
 const MODES=['light','dark'] as const; const half=(p:Palette,m:'light'|'dark')=>{const c=PALETTE_PREVIEWS[p][m];return `--pbg:${c.bg};--psb:${c.sidebar};--psf:${c.surface};--ptx:${c.text}`};
 /* The theme/navigation minis are painted with the chosen palette's colours so the whole section reflects it. */
 const miniVars=$derived(`--mini-light:${PALETTE_PREVIEWS[palette].light.bg};--mini-dark:${PALETTE_PREVIEWS[palette].dark.bg}`);
</script>
<div class="settings-section" style={miniVars}><div class="row stack"><div class="row-main"><div class="row-label">Theme</div></div><div class="row-ctl picks">{#each ['system','light','dark'] as option}<button class="pick" class:on={theme===option} type="button" onclick={()=>setTheme(option as Mode)}><span class="mini {option}"><i></i><i></i><b></b><b></b></span><span>{option==='system'?'Match system':option[0].toUpperCase()+option.slice(1)}</span></button>{/each}</div></div>
<div class="row stack"><div class="row-main"><div class="row-label">Accent colour · {ACCENT_LABELS[accent]}</div><div class="row-desc">This browser only.</div></div><div class="row-ctl swatches">{#each ACCENTS as a}<button type="button" class="swatch" class:on={accent===a} style={`--sw:${ACCENT_SWATCHES[a]}`} aria-label={ACCENT_LABELS[a]} aria-pressed={accent===a} onclick={()=>setAccent(a)}></button>{/each}</div></div>
<div class="row stack"><div class="row-main"><div class="row-label">Palette · {PALETTE_LABELS[palette]}</div><div class="row-desc">Neutral tones behind the accent, in light and dark. This browser only.</div></div><div class="row-ctl pals" role="radiogroup" aria-label="Palette">{#each PALETTES as p}<button type="button" class="pal" class:on={palette===p} role="radio" aria-checked={palette===p} onclick={()=>setPalette(p)} onpointerenter={(e)=>previewPalette(e,p)} onpointerleave={endPreview} onfocus={(e)=>previewPalette(e,p)} onblur={endPreview}><span class="pal-mini">{#each MODES as m}<span class="half" style={half(p,m)}><span class="sb"></span><span class="sf"><span class="ln"></span><span class="ln"></span></span></span>{/each}</span><span class="pal-name">{PALETTE_LABELS[p]}</span><span class="pal-desc">{PALETTE_DESCRIPTIONS[p]}</span></button>{/each}</div></div>
<div class="row stack"><div class="row-main"><div class="row-label">Navigation</div><div class="row-desc">Where your groups and collections live. This browser only.</div></div><div class="row-ctl picks">{#each [['classic','Top tabs'],['sidebar','Sidebar']] as option}<button class="pick" class:on={$layout===option[0]} type="button" onclick={()=>setLayoutPersisted(option[0] as 'classic'|'sidebar')}><span class="mini {option[0]}"><i></i><i></i><b></b><b></b></span><span>{option[1]}</span></button>{/each}</div></div></div>
<style>.picks{display:flex!important;gap:.6rem}.pick{width:106px;border:0;background:none;color:var(--text);text-align:left}.pick .mini{display:grid;grid-template-columns:repeat(2,1fr);gap:4px;height:66px;padding:18px 7px 7px;border:1.5px solid var(--border);border-radius:10px;background:var(--mini-light,#f8f9fb)}.pick .mini.dark{background:var(--mini-dark,#0f1117)}.pick .mini.system{background:linear-gradient(90deg,var(--mini-light,#f8f9fb) 50%,var(--mini-dark,#0f1117) 50%)}.pick .mini.sidebar{grid-template-columns:14px 1fr}.pick .mini i,.pick .mini b{background:#7b849733;border-radius:2px}.pick.on .mini{border-color:var(--accent);box-shadow:0 0 0 3px var(--accent-subtler)}.pick>span:last-child{display:block;margin-top:.4rem;font-size:.79rem}.swatches{display:grid!important;grid-template-columns:repeat(7,36px);gap:.55rem}.swatch{width:32px;height:32px;border-radius:50%;border:2px solid transparent;background:var(--sw)}.swatch.on{box-shadow:0 0 0 2px var(--surface),0 0 0 4px var(--sw)}
.pals{display:flex!important;flex-wrap:wrap;align-items:flex-start;gap:.6rem}.pal{width:106px;padding:0;border:0;background:none;color:var(--text);text-align:left;cursor:pointer}.pal-mini{display:grid;grid-template-columns:1fr 1fr;height:66px;border:1.5px solid var(--border);border-radius:10px;overflow:hidden;transition:border-color .15s,box-shadow .15s}.half{position:relative;padding:9px 6px 7px 16px;background:var(--pbg)}.half .sb{position:absolute;top:0;bottom:0;left:0;width:10px;background:var(--psb)}.half .sf{display:flex;flex-direction:column;gap:4px;height:100%;padding:7px 5px;border-radius:5px;background:var(--psf);box-sizing:border-box}.half .ln{display:block;height:3px;border-radius:2px;background:var(--ptx);opacity:.75}.half .ln+.ln{width:55%;opacity:.4}.pal:hover .pal-mini{border-color:var(--text-muted)}.pal.on .pal-mini,.pal:focus-visible .pal-mini{border-color:var(--accent);box-shadow:0 0 0 3px var(--accent-subtler)}.pal:focus-visible{outline:none}.pal-name{display:block;margin-top:.4rem;font-size:.79rem}.pal-desc{display:block;font-size:.7rem;color:var(--text-muted)}
@media(max-width:767px){.swatches{grid-template-columns:repeat(7,minmax(0,1fr))}.swatch{width:100%;aspect-ratio:1;height:auto}.pals{display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr))}.pal{width:auto}}</style>
