<script lang="ts">
 import {bulkEnrichProgress,enrichAllBookmarks,LOCAL_LINK_PREVIEWS_KEY,LOCAL_SOCKETHUB_URL_KEY} from '../../lib/enrich'; import {DEFAULT_SOCKETHUB_ENDPOINT} from '../../lib/link-metadata'; import {connected,items,userSettings,updateUserSettings} from '../../lib/stores'; import {needsEnrichment} from '../../lib/enrich'; import {showToast} from '../../lib/toast';
 const read=(k:string)=>{try{return localStorage.getItem(k)}catch{return null}}; const write=(k:string,v:string)=>{try{localStorage.setItem(k,v)}catch{}}; const remove=(k:string)=>{try{localStorage.removeItem(k)}catch{}}; let localOn=$state(read(LOCAL_LINK_PREVIEWS_KEY)!=='false'); const on=$derived($userSettings.linkPreviews!==false&&localOn); let custom=$state(!!($userSettings.sockethubUrl??read(LOCAL_SOCKETHUB_URL_KEY))); let endpoint=$state($userSettings.sockethubUrl??read(LOCAL_SOCKETHUB_URL_KEY)??''); const missing=$derived(Object.values($items).filter(i=>i.type==='bookmark'&&needsEnrichment(i)).length); const total=$derived(Object.values($items).filter(i=>i.type==='bookmark').length); const defaultHost=(()=>{try{return new URL(DEFAULT_SOCKETHUB_ENDPOINT).host}catch{return DEFAULT_SOCKETHUB_ENDPOINT}})();
 function toggle(v:boolean){localOn=v;write(LOCAL_LINK_PREVIEWS_KEY,String(v));if($connected)void updateUserSettings({linkPreviews:v?undefined:false})} function useDefault(){custom=false;endpoint='';remove(LOCAL_SOCKETHUB_URL_KEY);if($connected)void updateUserSettings({sockethubUrl:undefined})} function save(){const v=endpoint.trim();write(LOCAL_SOCKETHUB_URL_KEY,v);if($connected)void updateUserSettings({sockethubUrl:v||undefined})} function fetchAll(){void enrichAllBookmarks().then(r=>r&&showToast(`Updated ${r.updated} of ${r.total} bookmarks`)).catch(()=>showToast('Failed to fetch link previews'))}
</script>
<div class="settings-section"><div class="row"><div class="row-main"><div class="row-label">Show previews for saved links</div><div class="row-desc">Fetched via <a href="https://sockethub.org" target="_blank" rel="noreferrer">Sockethub</a>, an open multi-protocol gateway — the page title, description and image, without your browser ever contacting the site.</div></div><div class="row-ctl"><button type="button" class="switch" class:on aria-label="Show previews for saved links" aria-pressed={on} onclick={()=>toggle(!on)}></button></div></div>
{#if on}<div class="row"><div class="row-main"><div class="row-label">Fill in older bookmarks</div><div class="row-desc">{missing} of {total} saved links have no preview yet.</div></div><div class="row-ctl"><button class="btn" type="button" disabled={!missing||!!$bulkEnrichProgress} onclick={fetchAll}>{$bulkEnrichProgress?`${$bulkEnrichProgress.done}/${$bulkEnrichProgress.total}`:`Fetch ${missing} previews`}</button></div></div>
<div class="row stack"><div class="row-main"><div class="row-label">Sockethub server</div><div class="row-desc">Which Sockethub instance does the fetching on your behalf.</div></div><div class="row-ctl"><div class="seg"><button type="button" class:on={!custom} onclick={useDefault}>Default</button><button type="button" class:on={custom} onclick={()=>custom=true}>My own server</button></div>{#if custom}<div class="nested"><label for="preview-endpoint">Endpoint</label><input id="preview-endpoint" class="field mono" type="url" bind:value={endpoint} placeholder={DEFAULT_SOCKETHUB_ENDPOINT} onblur={save}/></div>{:else}<div class="nested">Runs at <code>{defaultHost}</code>, hosted by Inbox RS's author as a free service — see <a href="https://silverbucket.net" target="_blank" rel="noreferrer">silverbucket.net</a>.</div>{/if}</div></div>{/if}</div>
<style>.nested{margin-top:.6rem;padding:.75rem .9rem;border-left:2px solid var(--accent-line);background:var(--bg);border-radius:0 var(--radius-sm) var(--radius-sm) 0}.nested label{display:block;margin-bottom:.4rem;font-size:.76rem;color:var(--text-muted)}</style>
