import { describe, expect, it } from 'vitest';
import { buildMetadataContents } from './gen-plugin-metadata.mjs';

/**
 * `buildMetadataContents` produces the exact text written to
 * `packages/web/src/lib/plugin-downloads.generated.ts`. The web app
 * imports specific named exports from that file (`appVersion`,
 * `pluginArtifacts`) — testing the generator's output keeps the contract
 * with those imports honest, even though TypeScript would also catch
 * shape changes at compile time.
 *
 * Specifically pinned by these tests: per-artifact versions can diverge
 * from the web-app version (the whole point of release-bump.mjs), and
 * the URL filenames must use the artifact's own version, not the web's.
 */

describe('buildMetadataContents', () => {
  it('emits appVersion from the web version, not the extension version', () => {
    const out = buildMetadataContents({
      webVersion: '2.2.0',
      extensionVersion: '2.1.0',
      thunderbirdVersion: '2.1.1',
    });
    expect(out).toContain('export const appVersion = "2.2.0" as const;');
  });

  it('emits chromium and firefox URLs that use the extension version (not the web version)', () => {
    const out = buildMetadataContents({
      webVersion: '2.2.0',
      extensionVersion: '2.1.0',
      thunderbirdVersion: '2.1.1',
    });
    expect(out).toContain('"/downloads/inbox-rs-chromium-2.1.0.zip"');
    expect(out).toContain('"/downloads/inbox-rs-firefox-2.1.0.xpi"');
    expect(out).not.toContain('-2.2.0.zip');
    expect(out).not.toContain('-2.2.0.xpi');
  });

  it('emits thunderbird URL that uses the thunderbird version (independent of extension)', () => {
    const out = buildMetadataContents({
      webVersion: '2.2.0',
      extensionVersion: '2.1.0',
      thunderbirdVersion: '2.1.1',
    });
    expect(out).toContain('"/downloads/inbox-rs-thunderbird-2.1.1.xpi"');
  });

  it('exposes per-artifact `version` fields for UI display', () => {
    const out = buildMetadataContents({
      webVersion: '2.2.0',
      extensionVersion: '2.1.0',
      thunderbirdVersion: '2.1.1',
    });
    // Each artifact entry includes both `url` and `version`.
    expect(out).toMatch(
      /chromium:\s*\{[^}]*url:[^,]+,\s*version:\s*"2\.1\.0"/s,
    );
    expect(out).toMatch(/firefox:\s*\{[^}]*url:[^,]+,\s*version:\s*"2\.1\.0"/s);
    expect(out).toMatch(
      /thunderbird:\s*\{[^}]*url:[^,]+,\s*version:\s*"2\.1\.1"/s,
    );
  });

  it('marks the file as generated so it is not edited by hand', () => {
    const out = buildMetadataContents({
      webVersion: '1.0.0',
      extensionVersion: '1.0.0',
      thunderbirdVersion: '1.0.0',
    });
    expect(
      out.startsWith('// Generated by scripts/gen-plugin-metadata.mjs'),
    ).toBe(true);
  });

  it('emits valid TypeScript (uses `as const` for narrowed types)', () => {
    const out = buildMetadataContents({
      webVersion: '1.0.0',
      extensionVersion: '1.0.0',
      thunderbirdVersion: '1.0.0',
    });
    expect(out).toContain('} as const;');
    expect(out).toContain('export const appVersion');
    expect(out).toContain('export const pluginArtifacts');
    expect(out).toContain('export type PluginArtifactKey');
  });

  /**
   * REGRESSION: when the extension version lags the web version (the
   * whole point of decoupling), the URL must point at the file that
   * actually exists on disk — package-plugins.mjs names artifacts by
   * the extension's own version too. A mismatch here = 404 on the
   * downloads page.
   */
  it('keeps URL filename version in lockstep with the artifact version label', () => {
    const out = buildMetadataContents({
      webVersion: '3.0.0',
      extensionVersion: '2.0.0',
      thunderbirdVersion: '1.0.0',
    });
    // The chromium block should contain "2.0.0" in BOTH the URL and the
    // version label (and nowhere else within that block — i.e. no leak
    // of webVersion).
    expect(out).toMatch(
      /chromium:\s*\{\s*url:\s*"\/downloads\/inbox-rs-chromium-2\.0\.0\.zip",\s*version:\s*"2\.0\.0"/,
    );
    expect(out).toMatch(
      /thunderbird:\s*\{\s*url:\s*"\/downloads\/inbox-rs-thunderbird-1\.0\.0\.xpi",\s*version:\s*"1\.0\.0"/,
    );
  });
});
